language: objective-c
osx_image: xcode9

before_script:
    # Make log level less verbose. Temporarily undo if more info is needed
    - sudo log config --mode "level:default"

matrix:
  include:
    - language: python
      python: 3.6
      install: ""
      script: ./Scripts/push-output.sh
